name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test
    uses: hasundue/actions/.github/workflows/test-deno.yml@main
    secrets: inherit
