name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test
    uses: hasundue/actions/.github/workflows/test-deno.yml@main
    secrets: inherit

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
